config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'
  get  '/signup', to: 'users#new'
  post '/signup',  to: 'users#create'
  resources :users
  root 'lists#index'
  resources :lists
  resources :items, only:[:create, :destroy]
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :list
  validates :list_id, presence: true
end

app/models/list.rb
class List < ApplicationRecord
  has_many :items, dependent: :destroy
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  before_save { self.email = email.downcase }
  validates :name, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }
  has_many :lists
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include SessionsHelper
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  
  # 新規作成処理
  def create
    list = List.find(params[:list_id])
    @item = list.items.build(item_params)
    if @item.save!
      redirect_to list
    else
      edirect_to list, notice: "登録を失敗しました。"
    end
  end

  def destroy
    item = Item.find(params[:id])
    item.destroy
    redirect_back(fallback_location: items_path)
  end

  private

  # リクエストパラメータ
  def item_params
    params.require(:item).permit(:name, :amount)
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  # 一覧画面表示
  def index
    logged_in_user
    @lists = current_user.lists
  end

  # 詳細画面表示
  def show
    logged_in_user
    @list = List.find(params[:id])
    @items = @list.items.where.not(name: "")
    @item = @list.items.build
  end

  # 新規画面表示
  def new
    logged_in_user
    @list = List.new
  end

  # 新規作成処理
  def create
    list = current_user.lists.build(list_params)
    list.save!
    redirect_to list_path(list), notice: "リスト[#{list.title}]を登録しました。"
  end

  # 編集画面表示
  def edit
    logged_in_user
    @list = List.find(params[:id])
  end

  # 編集処理
  def update
    list = List.find(params[:id])
    list.update!(list_params)
    redirect_to list_path(list), notice: "リスト[#{list.title}]を編集しました。"
  end

  def destroy
    list = List.find(params[:id])
    list.destroy
    redirect_back(fallback_location: root_path)
  end

  private

  # リクエストパラメータ
  def list_params
    params.require(:list).permit(:title)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    # authenticateは、has_secure_passwordに生えているmethod
    if user && user.authenticate(params[:session][:password])
      # ユーザーログイン後にユーザー情報のページにリダイレクトする
      log_in user
      redirect_to user
    else
      # エラーメッセージを作成する
      render 'new'
    end
  end

  def destroy
    log_out
    redirect_to root_url
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      log_in @user
      redirect_to root_path
    else
      render 'new'
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  # 渡されたユーザーでログインする
  def log_in(user)
    session[:user_id] = user.id
  end

  # 現在ログイン中のユーザーを返す (いる場合)
  def current_user
    if session[:user_id]
      @current_user ||= User.find_by(id: session[:user_id])
    end
  end

  # ユーザーがログインしていればtrue、その他ならfalseを返す
  def logged_in?
    !current_user.nil?
  end

  # ログイン済みユーザーかの確認
  def logged_in_user
    unless logged_in?
      flash[:danger] = "Please log in."
      redirect_to login_url
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/items/edit.html.erb
<h1>Items#edit</h1>
<p>Find me in app/views/items/edit.html.erb</p>

app/views/items/index.html.erb
<h1>Items#index</h1>
<p>Find me in app/views/items/index.html.erb</p>

app/views/items/new.html.erb
<h1>Items#new</h1>
<p>Find me in app/views/items/new.html.erb</p>

app/views/items/show.html.erb
<h1>Items#show</h1>
<p>Find me in app/views/items/show.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ShoppingList</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% flash.notice if flash.notice.present? %>
    <%= flash.notice %>
    <%= yield %>
  </body>
</html>

app/views/lists/_form.html.erb
<div class="formWrap">
  <%= form_with model: list, class: 'titleForm' do |f| %>
    <p class="titleForm__name">タイトル</p>
    <%= f.text_field :title, class: 'inputTitle' %>
    <div class="btn-box btn-blackout">
      <%= f.submit '作成', class: 'createBtn' %>
    </div>
  <% end %>
</div>

app/views/lists/edit.html.erb
<div class="contentsTitle">
  <h1 class="contentsTitle__text">タイトル編集</h1>
</div>
<div class="main">
    <div class="container">
       <%= render partial:"form", locals: { list: @list } %>
    </div>
</div>

app/views/lists/index.html.erb
<%= stylesheet_link_tag 'lists' %>
<div class="mainTitle">
  <h1 class="mainTitle__text">LIST</h1>
</div>
<div class="listWrap">
  <ul class="list">
    <% @lists.each do |list| %>
      <li class="list__item">
        <p class="list__title">
          <%= link_to list.title, list_path(list),class: 'list__text' %>
          <%= link_to "", list, method: :delete, class: "far fa-trash-alt fa-lg list-trashicon" %>
        </p>
        <div calss="list__border"></div>
      </li>
    <% end %>
  </ul>
</div>
<div class="listBtn">
  <p class="listBtn__symbol">+</p>
  <%= link_to '追加', new_list_path,class: 'listBtn__text' %>
</div>

app/views/lists/new.html.erb
<div class="contentsTitle">
  <h1 class="contentsTitle__text">新規リスト作成</h1>
</div>
<div class="main">
  <div class="container">
    <%= render partial:"form", locals: { list: @list}%>
  </div>
</div>

app/views/lists/show.html.erb
<div class="mainTitle">
  <div class="listHeader">
    <p class="listHeader__btn"><%= link_to "＜戻る",  root_path, class: 'headerBtn' %></p>
    <p class="hayatyan"><%= @list.title %></p>
    <p class="listHeader__btn"><%= link_to '編集', edit_list_path, class: 'headerBtn' %></p>
  </div>
</div>
<% @items.each do |item| %>
<div class="panel-block">
  <div class="colum"><%= item.name %></div>
  <div class="icon">
    <% if item.name %>
      <%= link_to "", item, method: :delete, class: "far fa-trash-alt fa-lg trashicon" %><br>
    <% end %>
  </div>
</div>
<% end %>

<div class="addList">
  <%= form_with model: @item, url: items_path, class: 'addList__columns', local: true do |f| %>
    <%= f.text_field :name, class: 'addList__input' %>
    <%= hidden_field_tag :list_id, params[:id] %>
    <%= f.submit '追加', class: 'addList__btn' %>
    <% end %>
</div>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/users/new.html.erb
<div class="main">
  <div class="sineupForm">
    <div class="sineupFormWrap">
      <h1 class="sineupForm__name">新規登録</h1>
      <%= form_with(model: @user, local: true) do |f| %>
        <%= render 'shared/error_messages' %>
        <div class="inputBox">
          <%= f.label :ユーザー名, class: 'infoCategory' %>
          <%= f.text_field :name, class: 'inputInfo' %><br>

          <%= f.label :メールアドレス, class: 'infoCategory' %>
          <%= f.email_field :email, class: 'inputInfo' %><br>

          <%= f.label :パスワード, class: 'infoCategory' %>
          <%= f.text_field :password, class: 'inputInfo' %><br>
        </div>
        <%= f.submit '送信', class: 'sineupBtn' %>
      <% end %>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<%= @user.name %>, <%= @user.email %>